os: linux
dist: xenial

addons:
  apt:
    packages:
    - openvpn

before_install:
# To generate ovpn config file, uncomment following and provide arguments as required:
#- ./ovpn-writer.sh SERVER CA_CERT CLIENT_CERT CLIENT_KEY SHARED_SECRET > ./openvpn-configs/client.ovpn
- sudo openvpn ./openvpn-configs/client.ovpn &>>openvpn-client.log &

script: true